
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Ticket(String ticketno,String username,String age,String gender,String trainno,String Trainname,String From,String To,String Fair,String sd)
    {
        
         
        
        String TicketNumber = String.format((String)ticketno);
       String UserName = String.format(username);
      String Age = String.format(age);
       //String s=Integer.parseInt(age);
       String Gender = String.format(gender);
       String TrainNumber = String.format(trainno);
        String trainname = String.format(Trainname); 
        String from = String.format(From);
         String to = String.format(To);
          String fair = String.format(Fair);
          String date=String.format(sd);
       //========================================================================
       int refs= 1325 +(int) (Math.random()*4238);
       
       //========================================================================
       Calendar timer = Calendar.getInstance();
       timer.getTime();
       SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
       tTime.format(timer.getTime());
       SimpleDateFormat tDate = new SimpleDateFormat("dd:MMM:yyyy");
        tDate.format(timer.getTime());
       
       //========================================================================jtxtReceipt
       jTextArea1.append("\t\t  INDIAN RAILWAY \n " + 
               //"Reference:\t\t\t" + refs + 
               "\n=============================================================\t " + 
               "\n Ticket Number :\t\t"+TicketNumber + 
               "\n Person Name :\t\t"+UserName +
               "\n Age :\t\t"+Age +
               "\n Gender :\t\t"+Gender + 
               "\n Train Number :\t\t"+TrainNumber+ 
                "\n Train Name :\t\t"+Trainname +
               "\n From :\t\t"+From +
               "\n To :\t\t"+To + 
               "\n Fair :\t\t"+fair+ 
               "\n Booking Date :\t\t"+date+
               
               "\n=============================================================\t" +
               "\n Date : " + tDate.format(timer.getTime()) +
               "\t\t Time : " +tTime.format(timer.getTime()) +
               "\n\n Thank you \n");
                                            

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\Project0\\images (5).jpg")); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 320, 110, 30);

        jTextArea1.setBackground(new java.awt.Color(102, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 500, 320);

        setSize(new java.awt.Dimension(517, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try
{
// TODO add your handling code here:
Boolean printdata=jTextArea1.print();
if(printdata)
{
    JOptionPane.showMessageDialog(null,"Done Printing");
    setVisible(false);
    travel t=new travel();
    t.setVisible(true);
}
else
{
    JOptionPane.showMessageDialog(null,"Printing");
    
}
}
catch(PrinterException e)
{
    
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
       * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
